name: sips-connect
services:
  portal:
    image: abdoulhakim/sips-connect-portal:latest
    ports:
      - "3000:3000"
    environment:
      - NEXTJS_TLS_CERT=/app/certs/tls.crt
      - NEXTJS_TLS_KEY=/app/certs/tls.key
    restart: unless-stopped
    volumes:
      - ./tls-certs:/app/certs:ro
      - ./portal-db/db.json:/app/db.json:rw
    networks:
      - sips-network

networks:
  sips-network:
    driver: bridge